#############################################################################
# Makefile for building: qinvoicer
# Generated by qmake (2.01a) (Qt 4.7.3) on: mar oct 25 19:17:58 2011
# Project:  QInvoicer.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile QInvoicer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -Iinclude/view -Iinclude -Iinclude/persistence -Iinclude/model/domain -Ibuild
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/main.cpp \
		src/persistence/persistencemanager.cpp \
		src/persistence/sqlagent.cpp \
		src/view/invoiceeditor.cpp \
		src/view/qinvoicer.cpp \
		src/model/domain/invoice.cpp \
		src/model/domain/operation.cpp \
		src/model/domain/product.cpp build/moc_invoiceeditor.cpp \
		build/moc_qinvoicer.cpp \
		build/qrc_images.cpp
OBJECTS       = build/main.o \
		build/persistencemanager.o \
		build/sqlagent.o \
		build/invoiceeditor.o \
		build/qinvoicer.o \
		build/invoice.o \
		build/operation.o \
		build/product.o \
		build/moc_invoiceeditor.o \
		build/moc_qinvoicer.o \
		build/qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QInvoicer.pro
QMAKE_TARGET  = qinvoicer
DESTDIR       = 
TARGET        = qinvoicer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QInvoicer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile QInvoicer.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile QInvoicer.pro

dist: 
	@$(CHK_DIR_EXISTS) build/qinvoicer1.0.0 || $(MKDIR) build/qinvoicer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/qinvoicer1.0.0/ && $(COPY_FILE) --parents include/global.h include/persistence/persistencemanager.h include/persistence/sqlagent.h include/view/invoiceeditor.h include/view/qinvoicer.h include/model/domain/invoice.h include/model/domain/operation.h include/model/domain/product.h include/model/domain/types.h build/qinvoicer1.0.0/ && $(COPY_FILE) --parents resources/images.qrc build/qinvoicer1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/persistence/persistencemanager.cpp src/persistence/sqlagent.cpp src/view/invoiceeditor.cpp src/view/qinvoicer.cpp src/model/domain/invoice.cpp src/model/domain/operation.cpp src/model/domain/product.cpp build/qinvoicer1.0.0/ && (cd `dirname build/qinvoicer1.0.0` && $(TAR) qinvoicer1.0.0.tar qinvoicer1.0.0 && $(COMPRESS) qinvoicer1.0.0.tar) && $(MOVE) `dirname build/qinvoicer1.0.0`/qinvoicer1.0.0.tar.gz . && $(DEL_FILE) -r build/qinvoicer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_invoiceeditor.cpp build/moc_qinvoicer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_invoiceeditor.cpp build/moc_qinvoicer.cpp
build/moc_invoiceeditor.cpp: include/model/domain/types.h \
		include/view/invoiceeditor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/view/invoiceeditor.h -o build/moc_invoiceeditor.cpp

build/moc_qinvoicer.cpp: include/model/domain/types.h \
		include/view/qinvoicer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) include/view/qinvoicer.h -o build/moc_qinvoicer.cpp

compiler_rcc_make_all: build/qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/qrc_images.cpp
build/qrc_images.cpp: resources/images.qrc \
		resources/images/volumebuy.png \
		resources/images/volume.png \
		resources/images/saleinvoice.png \
		resources/images/exit.png \
		resources/images/loadinvoice.png \
		resources/images/product.png \
		resources/images/loadproduct.png \
		resources/images/volumesale.png \
		resources/images/buyinvoice.png \
		resources/images/appicon.png \
		resources/images/unpaid.png
	/usr/bin/rcc -name images resources/images.qrc -o build/qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

build/main.o: src/main.cpp include/view/qinvoicer.h \
		include/model/domain/types.h \
		include/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/persistencemanager.o: src/persistence/persistencemanager.cpp include/persistence/persistencemanager.h \
		include/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/persistencemanager.o src/persistence/persistencemanager.cpp

build/sqlagent.o: src/persistence/sqlagent.cpp include/persistence/sqlagent.h \
		include/persistence/persistencemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/sqlagent.o src/persistence/sqlagent.cpp

build/invoiceeditor.o: src/view/invoiceeditor.cpp include/view/invoiceeditor.h \
		include/model/domain/types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/invoiceeditor.o src/view/invoiceeditor.cpp

build/qinvoicer.o: src/view/qinvoicer.cpp include/view/qinvoicer.h \
		include/model/domain/types.h \
		include/view/invoiceeditor.h \
		include/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qinvoicer.o src/view/qinvoicer.cpp

build/invoice.o: src/model/domain/invoice.cpp include/model/domain/invoice.h \
		include/model/domain/types.h \
		include/model/domain/operation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/invoice.o src/model/domain/invoice.cpp

build/operation.o: src/model/domain/operation.cpp include/model/domain/operation.h \
		include/model/domain/product.h \
		include/model/domain/types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/operation.o src/model/domain/operation.cpp

build/product.o: src/model/domain/product.cpp include/model/domain/product.h \
		include/model/domain/types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/product.o src/model/domain/product.cpp

build/moc_invoiceeditor.o: build/moc_invoiceeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_invoiceeditor.o build/moc_invoiceeditor.cpp

build/moc_qinvoicer.o: build/moc_qinvoicer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_qinvoicer.o build/moc_qinvoicer.cpp

build/qrc_images.o: build/qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_images.o build/qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

